<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-11-10 22:58

import django.db.models.deletion
from django.db import migrations, models
=======
# Generated by Django 4.2.19 on 2025-02-24 04:09

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 8bb8dda1a481287b184dd5feb1ec3e7f69e36ec3


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
=======
                ('name', models.CharField(max_length=255)),
>>>>>>> 8bb8dda1a481287b184dd5feb1ec3e7f69e36ec3
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=200)),
=======
                ('title', models.CharField(max_length=255)),
>>>>>>> 8bb8dda1a481287b184dd5feb1ec3e7f69e36ec3
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='relationship_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=150)),
=======
                ('name', models.CharField(max_length=255)),
>>>>>>> 8bb8dda1a481287b184dd5feb1ec3e7f69e36ec3
                ('books', models.ManyToManyField(related_name='libraries', to='relationship_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=100)),
=======
                ('name', models.CharField(max_length=255)),
>>>>>>> 8bb8dda1a481287b184dd5feb1ec3e7f69e36ec3
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to='relationship_app.library')),
            ],
        ),
    ]
